### ISSUE TITLE
Design New Homepage Layout Spec

### ISSUE THREAD

**Issue by jordan-pieces** [pieces-app/example-ts#11]
## Issue 

We need to create a clean environment for the index.tsx page where all of our components are rendered. Currently the UI has no style and does not really contain any specific styling. We have a drafted document on our design elements that @laurin-at-pieces put together to offer some base inspiration around these components.

PDF Here: 
[combinepdf (5).pdf](https://github.com/pieces-app/example-ts/files/13397816/combinepdf.5.pdf)

## Two main objectives 

- [ ] create a layout design that does not cause the user to scroll and functions as a web application 
- [ ] create a drafted version in figma, sketch, or even canva and share

**Comment by malakii-dev** [comment]
Hi @Sophyia7 i would like to get assigned to this task

**Comment by Sophyia7** [comment]
@malakii-dev You are good to go! Ensure you read the [designer contribution guide](https://github.com/pieces-app/example-ts/blob/sophyia/CONTRIBUTING.md#contributing-design)

Reach out if you have any questions.

**Comment by jordan-pieces** [comment]
@malakii-dev @Sophyia7 do we have any updates around this project? We currently have this issue here #3 that addresses some updates to the homepage and want to make sure that you both are in the loop, once that PR is opened it is going to be reviewed and discussed before merge, and we can connect before all that takes place. just let me know where you currently stand :) and apologies for the slight overlap here

**Comment by jordan-pieces** [comment]
sounds good @malakii-dev let us know when you are in a good spot and want to share 👍

**Comment by jordan-pieces** [comment]
@Sophyia7 @malakii-dev do you have any information on the status of this issue?

**Comment by jordan-pieces** [comment]
i have just attached an issue that will close the need for this one. i have not heard any updates on the status of this so far and we need to continue adding more information to the example-ts project itself
