### ISSUE TITLE
Update UI and Add Improved Styling

### ISSUE THREAD

**Issue by jordan-pieces** [pieces-app/example-ts#3]
The current UI in your browser is very light and goes beyond your available window space when loading the page. There are a few improvements that could be made here, but opening this up to others who would like to contribute.

There is not a particular direction laid out yet, but will create some rough sketches in a day or two to give everyone some time.

I will add any ideas in the comments that i have, but please add anything that seems like a good direction. Lets keep this conversation high level and focused on the UI of the application.

**Comment by Pooja1672** [comment]
HI @jordan-pieces , I would like to work on this issue can you please assign it to me?

**Comment by jordan-pieces** [comment]
@Pooja1672 thats amazing would absolutely love your contributions on this project. Just a few questions as you are getting started as we are developing our contribution guide currently.

- Are you already in our discord? Curious for communication, and we can always communicate via github primarily as well.

- Can you outline a few of the steps in your process to serve as checkpoints for the UI upgrade? 

- Would you like for me to design what the UI goal is and give you a mockup that you can follow for the project, or would you rather just go for it your self? 

Let me know and I can get you any resources to get started if you need them! Excited to have you as the first contributer to our getting started project!! 😃

**Comment by jordan-pieces** [comment]
hey @Pooja1672 just wanted to check in - let me know if you have had any time to review this up above/have any questions

**Comment by pythonistical** [comment]
Hi Jordan, I have seen that the assignee to this issue has gone afk. So, can you reassign it to me? I am on the Pieces Discord server. I go by the name Pythonistic. Just send me the link to the website and the repo and I will start to work right away

**Comment by jordan-pieces** [comment]
@pythonistical to view the page that is needed to be redesigned, you can pull the project and simply build it with locally and run to view the UI, or see it in its bismal shape here: 

![Screenshot 2023-11-27 at 2 25 55 PM](https://github.com/pieces-app/example-ts/assets/55861512/f62388ce-edb5-4f01-9988-37c624b9c7aa)

Also see my comment on your other issue before getting started, want to make sure we keep each task fairly scoped

**Comment by pythonistical** [comment]
@jordan-pieces can you now assign me to this issue

**Comment by pythonistical** [comment]
![pieces-UI](https://github.com/pieces-app/example-ts/assets/142655673/ce57a297-084e-4d3f-a5c6-553385bba362)
I have done the project, where should I post the code and the files I have used? I don't exactly see a repo dedicated to it. And is any improvement needed to it?

**Comment by jordan-pieces** [comment]
@pythonistical i can review this and get back to you - great work on getting the UI cleaned up ☺️ you can open a PR into the [example-ts](https://GitHub.com/pieces-app/example-ts) project.

let me know how that goes and if you need any assistance - we may have resources ready that we can send your way. go ahead and tag me as a reviewer and we can go from there 👍🏾

**Comment by pythonistical** [comment]
@jordan-pieces can I get access to the assets folder so I can upload code dependencies?

**Comment by jordan-pieces** [comment]
@pythonistical i would just take the repo, fork it, and then open up a PR into this repo

**Comment by jordan-pieces** [comment]
@pythonistical were you able to get the branch up and running after forking the repo?

**Comment by pythonistical** [comment]
Yes, I can run the script on my computer, because I have downloaded the files. However, I need access to the assets folder to run the icons and logos on the webpage online, Not a big fan of SVG's here.

**Comment by jordan-pieces** [comment]
can you add a link to your GH fork here? i wold love to check it out and then i can help give some more clear instruction  👍

**Comment by pythonistical** [comment]
https://github.com/pythonistical/example-ts

**Comment by Sophyia7** [comment]
@jordan-pieces has this issue been resolved?

**Comment by jordan-pieces** [comment]
I am going to close this issue for now, as the branch that is located on #35 was the origin and i tried to add in some of the suggestions from @pythonisitical. Since this PR was configured around the `public/index.html` statically generated file, it is not setup to support react or future development. 

I think for now @pythonistical we take this as a learning opportunity, and you take some time to read through the notes that I left inside of the PR and code. **I will add them to the other PR in screenshots in the comments of the PR**

**Comment by jordan-pieces** [comment]
see #35
