### ISSUE TITLE
Setup Github Action for building and testing the project

### ISSUE THREAD

**Issue by shivay-at-pieces** [pieces-app/example-ts#31]
There is a need to automate the build process for the example TS project using GitHub Actions. 
Create a build.yml file to build and test the project.

**Comment by RohanMishra315** [comment]
Hey @jordan-pieces Can I take up the issue.

**Comment by jordan-pieces** [comment]
Absolutely - let us know if you have any questions on the specifics of this issue, there are example scripts in the package.json for cleaning, installing, and building the project. 

Here are a few top level things to try and accomplish: 
- [ ] successfully build the /dist folder via GH actions 
- [ ] create a single test inside of a new `/test` directory

**Comment by jordan-pieces** [comment]
closing this - PR merged 👍
