### ISSUE TITLE
Add typescript and react in the package.json dependencies

### ISSUE THREAD

**Issue by shivay-at-pieces** [pieces-app/example-ts#32]
The current configuration lacks TypeScript and React in the package.json dependencies, which results in failures during GitHub Actions runs.  we need to add TypeScript and React to the project dependencies in the package.json file.

**Comment by derajohnson** [comment]
Can i work on this @jordan-pieces?

**Comment by jordan-pieces** [comment]
@derajohnson absolutely let me know how it goes ! 🥇
