### ISSUE TITLE
Refactor Inline Styles to Local CSS in Component Files

### ISSUE THREAD

**Issue by Sophyia7** [pieces-app/example-ts#37]
**Problem Statement:**
Our components have inline styles, making the code less maintainable and harder to update. To improve this, we want to refactor the inline styles into local CSS within each component file. This will enhance readability, modularity, and ease of maintenance.

**Proposed Changes:**
1. Identify components with inline styles.
2. Create a corresponding CSS file for each component.
3. Move inline styles from the component file to the newly created CSS file.
4. Ensure that the CSS file is still local to the component for better encapsulation.
5. Update the component file to reference the new CSS file.

**Expected Outcome:**
The codebase will be cleaner, more modular, and easier to maintain. The separation of concerns will allow for better organization and future updates to styles without affecting the component logic.

**Comment by Arindam200** [comment]
Can I Work on this?

**Comment by jordan-pieces** [comment]
to be completed following #43 initial styling and laying out the global CSS file

**Comment by Arindam200** [comment]
@jordan-pieces 

Just a follow-up question. 

"Create a corresponding CSS file for each component."

Here it's mentioned to create a corresponding CSS file for each component. 

So should I put the inline styles in the global.css file? 


Or make separate css files for each one

Example: 

For the button component

- components
    ।
    ।-Button
            ।- Button.tsx
            ।- Button.css

**Comment by jordan-pieces** [comment]
@Arindam200 ah yes there is a bit of a discrepancy here. apologies for that, why don't we follow your example here for the button component and implement that for the other components. we can save the global CSS file for a little later on or for some parts of the application that have not been turned into components yet

**Comment by Arindam200** [comment]
@jordan-pieces I think we can apply this approach. For the components we should use the specified CSS file ( Example: For button components `button.css`) 

And we can have a global.css file for the larger implementations like the styles of Scrollbar.

This will make the code more readable as well, otherwise if we directly use only one `Global.css`, It will be a bit confusing for us to understand those codes properly! 

What do you think?

**Comment by jordan-pieces** [comment]
@Arindam200 this is perfect, excited to see this in action, and the team working on the hover styles could definitely use this PR. apologies for the slow response coming back from the holidays! 

here is that issue for reference: #42 

lets use the `Global.css` and the `button.css` and we will use it in this way. would love to have a comment on the header of the `Global.css` file that reflects this intent! let me know when you have a PR ready to go.
