### ISSUE TITLE
Add Windows Support to `npm run start` and `npm run clean` Commands

### ISSUE THREAD

**Issue by Sophyia7** [pieces-app/example-ts#38]
**Problem Statement:**
The current setup of the `npm run start` and `npm run clean` commands is not compatible with Windows environments. This is causing issues for developers using Windows as their operating system. To enhance cross-platform compatibility, we need to add Windows-specific commands for these scripts.

**Proposed Changes:**

1. Update `npm run start` Script
2. Update `npm run clean` Script

Developers using Windows should be able to run `npm run start` and `npm run clean` without encountering compatibility issues. 

Make sure to test the updated scripts on a Windows environment to ensure they work as expected. If you encounter any issues or have questions, feel free to reach out for assistance.

**Comment by RohanMishra315** [comment]
Hey @Sophyia7 Can I take it?

**Comment by guranshdeol** [comment]
hey @Sophyia7 , i would like to work on this issue!

**Comment by jordan-pieces** [comment]
@RohanMishra315 can you work together with @guranshdeol to get this done? i know this is not a super large issue but sharing your findings, research or just thoughts here would be great

**Comment by guranshdeol** [comment]
@jordan-pieces Thanks for assigning the issue, i will get back with proposed changes soon :)

**Comment by jordan-pieces** [comment]
Awesome! sounds good

**Comment by RohanMishra315** [comment]
Hey @guranshdeol If you need some help, you can reach out to me !

**Comment by guranshdeol** [comment]
Sure @RohanMishra315 !!

**Comment by jordan-pieces** [comment]
I went ahead and merged this PR as we are in need of the windows support given by @RohanMishra315 - @guranshdeol do you have any updates here that i can review? otherwise we can get you going on another issue
