### ISSUE TITLE
Implement Timer to Hide "You're Connected" Text

### ISSUE THREAD

**Issue by Sophyia7** [pieces-app/example-ts#39]
**Problem Statement:**
Upon connecting to the Pieces OS, there is a need to enhance the user experience by implementing a timer that automatically hides the **"You're Connected"** text and shrinks the button after a certain duration.

**Proposed Changes:**
1. Identify the element containing the "You're Connected" text and the associated button.
2. Implement a timer function in the relevant JavaScript file.
3. Upon connection, trigger the timer to start.
4. After the specified duration, hide the text and apply the button shrink effect.

Users will experience a more streamlined interface where the **"You're Connected"** text disappears, and the button shrinks after a set period, providing a cleaner visual feedback post-connection.

**Comment by agrim0312** [comment]
hey @Sophyia7 can i work on this

**Comment by jordan-pieces** [comment]
@agrim0312 sounds great - once this task is completed another interesting timer related feature would be around ensuring a live connection to pieces os, where the connection check is synchronous and reacts when pieces os is running or closed without having to refresh the page.

first knock out the about task but just something for you to think about as well 👍
