### ISSUE TITLE
Abstractions + File Segmentation to Support Future Additions  

### ISSUE THREAD

**Issue by jordan-pieces** [pieces-app/example-ts#4]
The `example-ts` project is mainly utilizing the index.ts file and all functions are being created, exported, and called from that location. 

Would love to add more file structure here for components and organization outside of the primary files that are present now just to create a more simplistic way to find different elements.

If you are planning to work on this specific issue, please include a folder structure document that outlines the top level of what you are thinking about this organization.

**Comment by Pratere** [comment]
Hi Jordan, I'm still trying to learn more about standard typescript patterns, but my thought would be the following structure:

- src/
  - index.tsx
  - app/
    - App.tsx
    - components/
      - Asset.tsx
        - createAsset()
        - deleteAsset()
      - TextInput.tsx
      - ...
    - utils/
      - Connect.tsx
        - connect()
      - ...

Please let me know if I'm off track, I'm not sure what you meant by "folder structure document". Thanks!

**Comment by jordan-pieces** [comment]
@Pratere this is perfect! will definitely have to work on some better wording for these issues. 

if you want to open up a pr implementing this structure i can review it and get it updated for everyone to use 😁

**Comment by Pratere** [comment]
@jordan-pieces no worries about the wording, just want to make sure we're on the same page! I will try and get a draft PR open this evening. Thanks!

**Comment by jordan-pieces** [comment]
@Pratere amazing ill take a look this evening when you get that up - and thanks for clarifying glad we are on the same page 👍
