### ISSUE TITLE
Display Current Version in "You're Connected" Screen

### ISSUE THREAD

**Issue by Sophyia7** [pieces-app/example-ts#40]
**Problem Statement:**
We want to display the current version in the "You're Connected" screen to enhance user awareness and provide additional information. This will help users quickly identify the version they are connected to.

**Proposed Changes:**
1. Identify the location in the codebase where the "You're Connected" pill is rendered.
2. Retrieve the current version information programmatically (e.g., from a configuration file or build metadata).
3. Update the rendering logic to include the current version in the "You're Connected" pill.

**Expected Outcome:**
Upon connecting to Pieces OS, users will see the "You're Connected" pill, now enhanced with information about the current version, providing a clear reference to the version they are using.

**Comment by derajohnson** [comment]
@Sophyia7 can i take up this issue?

**Comment by jordan-pieces** [comment]
@derajohnson just want to go ahead and give you the green light on this issue - expect updates on the search endpoint with some examples tomorrow 👍
