### ISSUE TITLE
Implement Button Functionality for Launching Pieces OS

### ISSUE THREAD

**Issue by Sophyia7** [pieces-app/example-ts#41]
**Problem Statement:**
Currently, when Pieces OS is not connected, the UI lacks a functional aspect to initiate the connection. To improve user interaction, we want to add button functionality to the "**Not Connected**" button, allowing users to launch Pieces OS by clicking it.

**Expected Outcome:**
Users will be able to launch Pieces OS by clicking the **"Not Connected"** button, enhancing the user experience and providing a straightforward way to establish a connection.

**Comment by jordan-pieces** [comment]
@nathan-courtney-pieces just wanted to double check that we have the proper support via a URL scheme for launching pieces OS programmatically in the browser?

**Comment by nathan-courtney-pieces** [comment]
pieces://launch

**Comment by agrim0312** [comment]
@Sophyia7 @jordan-pieces I have implemented it and created a PR can you assign it to me.
Thanks
