### ISSUE TITLE
Upgrade Buttons with Hover Styles

### ISSUE THREAD

**Issue by Sophyia7** [pieces-app/example-ts#42]
**Problem Statement:**
The current styling of buttons lacks interactive feedback, and we want to enhance the user experience by adding hover styles to the buttons. This improvement will provide visual cues to users when they hover over the buttons, making the interface more engaging.

**Proposed Changes:**
1. Identify the CSS styles related to buttons in the project.
2. Introduce new styles using the `:hover` pseudo-class for buttons.
3. Ensure compatibility and responsiveness across different browsers.

Upon hovering over buttons, users will experience an enhanced visual feedback, making the interface more interactive and polished.

**Comment by pythonistical** [comment]
@Sophyia7 I will like to be assigned to this issue

**Comment by UtkarshUmre** [comment]
hey @Sophyia7 I would like to work on this issue. Can you assign this to me?

**Comment by joseph0819** [comment]
Hello @Sophyia7 I would like to assigned to this task

**Comment by Sophyia7** [comment]
@pythonistical was the first to request this issue. I have to assign it to him. Cc: @jordan-pieces

**Comment by Sophyia7** [comment]
@joseph0819 @UtkarshUmre  apologies. Check out other issues. We would be adding more good first issues today as well. Please an eye out for it.

**Comment by pythonistical** [comment]
@Sophyia7 where do I have to build these buttons? I don't exactly see a link to a folder where I can build

**Comment by jordan-pieces** [comment]
@pythonistical @UtkarshUmre @joseph0819  i went ahead and assigned all of you to this issue, and would love to see some collaboration here to get this done where possible. 

You can all use the `/button.tsx` folder for working on your specific button. If you would like to include a few different styles of button in this file from each of you, we can select one following the collaboration. Talk amongst yourselves here and lets see what we can make happen. 

here is a cool css and html button that i really love and would be curious to see the difficulty here (i understand it is likely very high as i am testing this build soon myself)

**Comment by pythonistical** [comment]
@UtkarshUmre @joseph0819 I have come up with this design, you copy paste the code and run it online here https://www.w3schools.com/html/tryit.asp?filename=tryhtml_basic
`<html>
    <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
        <style>
            body{font-family: "poppins",serif}
            .button {
  background-color: #04AA6D; /* Green */
  border: none;
  color: white;
  padding: 16px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  transition-duration: 0.4s;
  cursor: pointer;
  border-radius: 10%
}
.button_design {
  background-color: white;
  color: black;
  border: 2px solid #555555;
}

.button_design:hover {
  background-color: #555555;
  color: white;
}
</style>
</head>
<body>
    <span class="button button_design">Pieces</span>
</body>
</style>
</head>
</html>`

**Comment by pythonistical** [comment]
@UtkarshUmre @joseph0819 Try running this code here https://www.w3schools.com/html/tryit.asp?filename=tryhtml_basic or offline
```html
<html>
    <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
        <style>
            body{font-family: "poppins",serif}
            .button {
  background-color: #04AA6D; /* Green */
  border: none;
  color: white;
  padding: 16px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  transition-duration: 0.4s;
  cursor: pointer;
  border-radius: 10%
}
.button_design {
  background-color: white;
  color: black;
  border: 2px solid #555555;
}

.button_design:hover {
  background-color: #555555;
  color: white;
}
</style>
</head>
<body>
    <span class="button button_design">Pieces</span>
</body>
</style>
</head>
</html>
```

**Comment by UtkarshUmre** [comment]
> @UtkarshUmre @joseph0819 Try running this code here https://www.w3schools.com/html/tryit.asp?filename=tryhtml_basic or offline
> 
> ```
> <html>
>     <head>
>         <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
>         <style>
>             body{font-family: "poppins",serif}
>             .button {
>   background-color: #04AA6D; /* Green */
>   border: none;
>   color: white;
>   padding: 16px 32px;
>   text-align: center;
>   text-decoration: none;
>   display: inline-block;
>   font-size: 16px;
>   margin: 4px 2px;
>   transition-duration: 0.4s;
>   cursor: pointer;
>   border-radius: 10%
> }
> .button_design {
>   background-color: white;
>   color: black;
>   border: 2px solid #555555;
> }
> 
> .button_design:hover {
>   background-color: #555555;
>   color: white;
> }
> </style>
> </head>
> <body>
>     <span class="button button_design">Pieces</span>
> </body>
> </style>
> </head>
> </html>
> ```
> 
> Do you have any suggestions/ideas?
> 
> ![Screenshot 2024-01-08 092145](https://private-user-images.githubusercontent.com/142655673/294809725-bb283e8b-0139-4723-a455-aa96077a5427.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NDQzOTEsIm5iZiI6MTcwNDc0NDA5MSwicGF0aCI6Ii8xNDI2NTU2NzMvMjk0ODA5NzI1LWJiMjgzZThiLTAxMzktNDcyMy1hNDU1LWFhOTYwNzdhNTQyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQyMDAxMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MGYxMjExZDQ4NmMwMzRkN2UwODI2YTgwZjIxMWIxMDVkZTdhMThjMTQwYmY3Nzg4YTI4Mjk0YTNiOTg1ODE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.d5Iy-eD0muS0gSI1-IXnOkCWpE5w5njX9aSIv-hvQ2A)

hey @pythonistical i think you've done work to solve this issue, please let me know if you need any assistance

**Comment by pythonistical** [comment]
@UtkarshUmre No thanks I don't need assistance, I have opened a pull request on this

**Comment by jordan-pieces** [comment]
@UtkarshUmre do you still have this code/ are willing to open up a PR with the above code that you shared added? Would love to get that in and can also make this available for @pythonistical to see how it works in action

**Comment by jordan-pieces** [comment]
*nudge* just to re-elevate

**Comment by jordan-pieces** [comment]
Im going to close this for now, as it is not endpoint centric and we could just add this in during a style sprint in the future
