### ISSUE TITLE
Change Scrollbar Styles for a Cleaner Look

### ISSUE THREAD

**Issue by Sophyia7** [pieces-app/example-ts#43]
**Problem Statement:**
The current scrollbar styles appear clunky and do not align with the desired aesthetics of the application. We aim to update the scrollbar styles to improve the overall visual appeal and user experience to achieve a cleaner and more modern look.

After implementing the changes, the scrollbars throughout the application will have a refined appearance, contributing to a more polished and visually pleasing user interface.

**Comment by Arindam200** [comment]
I would like to work on this! 

Can you provide some more details?

**Comment by jordan-pieces** [comment]
Hey @Arindam200 for sure - the goal here is to implement CSS in this react environment to gain access to `:hover` pseudo classes that are available in CSS. V1 of this can just be implementing a global CSS file and removing the background color of the scrollbar, and aesthetically improving its appearance. 

a huge advantage will be the implementation of the global CSS file and will support moving a lot of our styles into classes that can be shared from there.

let me know if you have any more questions around this! 

also connected to #37 - if you want to handle this step first and then move on to the larger refactor that would be fantastic! 💯

**Comment by jordan-pieces** [comment]
@Arindam200 not of the background div, but the backgrounds on the scrollbars themselves - bringing them closer to the something like this: 

![Screenshot 2023-12-18 at 10 34 43 AM](https://github.com/pieces-app/example-ts/assets/55861512/a37c7698-f8d7-499d-968c-b61ec70f0869)

**Comment by Arindam200** [comment]
@jordan-pieces 

So I made something like this, is it okay?

![image](https://github.com/pieces-app/example-ts/assets/109217591/5bda00f1-15df-4be1-b144-9aba1f4065aa)

**Comment by Arindam200** [comment]
Hey @jordan-pieces Another Point, I want to mention is that we don't use the scroll bar on the x-axis of the code snippets grid layout,

So, It's unnecessary to have a scrollbar on the x-axis.

I have removed that and, it looks like this: 
![image](https://github.com/pieces-app/example-ts/assets/109217591/3e0a05ae-f819-49c2-a864-1cd214bd93c4)

Is it okay?

**Comment by Arindam200** [comment]
Hey @jordan-pieces ! Should I make a PR? 

or I need to Change something ?

**Comment by jordan-pieces** [comment]
@Arindam200 apologies as we have been all getting back from the holidays - go ahead and open a PR and i can review, but you will note that there have been some changes to the parent repo that went in before, so i would see if you can get your branch updated or start from  a new branch and i can review 👍 

if you have other questions feel free to ask them here! Hope you are doing well

**Comment by Arindam200** [comment]
Ok Thanks. I'll be sending the PR today.

**Comment by jordan-pieces** [comment]
following that i am excited to see your work on the issue here #37 to support a few contributors on issue #42 for button styles 👍

**Comment by Arindam200** [comment]
I have created One PR and Will send another PR today
