### ISSUE TITLE
Too many permissions being requested on github

### ISSUE THREAD

**Issue by dealvz** [pieces-app/example-ts#56]
Requested permissions on Github:

![image](https://github.com/pieces-app/example-ts/assets/5633757/d65b8e68-d063-4a41-90ea-22f87926d1a4)

The permissions for gists make sense. However read/write access to private repos doesn't seem necessary, and having access to orgs is a non starter.

I suggest these permissions are trimmed down to only what is absolutely necessary.

**Comment by jordan-pieces** [comment]
hey @dealvz thank you for sharing this feedback here.

@mason-at-pieces can go into more details here on what is actually requested and why it is needed in this. if you have more questions following his response let me know and we can continue this conversation 👍

**Comment by mason-at-pieces** [comment]
Hey @dealvz! We do not currently use any private information and will never without the user's permission, but the main reason we decided to request those permissions is so that in the future, when we add features that allow you to reference a public/private repo in a copilot chat, we won't have to re-request access to your GH account to get those extra permissions.

Hopefully that makes sense.

**Comment by dealvz** [comment]
@jordan-pieces @mason-at-pieces Thanks for the response. I'm really enjoying the app, super useful and I'm glad it exists, you guys provide a solution that was sorely needed in an interesting niche.

I understand as an up and coming startup, it makes sense to want as many permissions as possible in anticipation of future releases/features. However, as a user and member of an organization with potentially sensitive data, eventual potential hipaa considerations, it's simply a non-starter to grant the permissions requested even though its ultimately up to the organization to allow these permissions. That also extends, to a lesser extent, to private repositories. At any given time I might be working on several personal projects which I may or may not feel comfortable opening up to outside parties and/or companies such as OpenAI. If the data gathered is not used for training purposes I'd make that abundantly clear. However with personally private repos we are often careless during the development process with api keys/env variables. I'd much prefer a company which requests the minimum necessary permissions to accomplish their current services, and then subsequently grant access as other needs arise. Otherwise I'd be granting permissions and trusting future intentions as well as the security capabilities of said company.

As it stands, I'd choose to authenticate with google or not at all, and I could not recommend the application to my company, which may be the case for other organizations and detrimental to adoption amongst enterprise customers.

Nonetheless I appreciate the response and wish you all the best with this product. I'll continue to use and follow your progress. Feel free to close this issue at your convenience.

**Comment by mark-at-pieces** [comment]
@dealvz Sorry for the delayed response.

I'm glad to see that your enjoying Pieces. I can see that your concerned with the permissions requested by the Github integration. I would love to chat more about Pieces and what we do with our Github integration as it currently stands today as well as where we are going with regard to this integration.

In production right now, we have a couple of things connect your Github account this will enable you to sign up a Personal VPC within our own backend that we use for your personal shareable links. This enables us to also Post Snippets as gists IFF you want to share via a Gist. As well this will also enable use to import your current Gists.

Not in production however will be coming soon is discovery from your own repos, searching across your repos for useful workflow materials, and many more features. I would also like to let you know that we 100% do NOT gather any data from your Github. This integration is simply here for you, as a user, to provide a better experience within Pieces as well as enable you, as a developer, to be more productive given the additional context.

I can also resonate wanting to give a company with the minimum amount of permission needed for each and every integration and we would have these if they were not 100% necessary. Another thing, is that the Github integration is an opt in feature and is NOT required what so ever, so it is really awesome that you authenticated with Google instead. As well authentication with google will grant you access to your own VPC and the ability to share your snippets (backup/sync coming soon) however nothing with regard to Github which is totally understandable. I hope you continue to enjoy Pieces.

If you would like talk on a call or continue to chat over this Github issue I'm more than willing to answer any and all questions you may have. We really appreciate you reaching out!

**Comment by jordan-pieces** [comment]
@dealvz @mark-at-pieces planning to close this issue in the next 24 hours, please update if any further conversation is needed here or if you can be assisted any fiurther 👍
