### ISSUE TITLE
Add Installation Process using NVM

### ISSUE THREAD

**Issue by Sophyia7** [pieces-app/example-ts#6]
### Issue
We need to run this project on all environments(MacOS, Windows OS, and Linux OS) to allow contributors to choose what package manager they want to use. Currently, the process to set up the project locally uses NPM. 

### Solution
Update the existing installation process to incorporate Node Version Manager (NVM) alongside the existing NPM installation method. You can create a divider to separate the package manager installation processes. This should be done on the ReadMe.md file.

**Comment by derajohnson** [comment]
Hi @jordan-pieces i would like to take up this issue

**Comment by jordan-pieces** [comment]
@derajohnson that sounds great - this is assigned to you and you can open up a branch and connect it to this issue when you have some progress to share :) best of luck!! let me know if you have any questions or need anything to get started.

**Comment by derajohnson** [comment]
Just to be clear, what version of node do we want to install using NVM? @jordan-pieces @Sophyia7
