### ISSUE TITLE
Messages Not Disappearing After Sending in Copilot Chat

### ISSUE THREAD

**Issue by Sophyia7** [pieces-app/example-ts#60]
### Problem statement
When interacting with Copilot chat, you will notice that messages are not disappearing after being sent. 

**Expected Behavior:**
The sent message should disappear after being sent for a cleaner and more intuitive user experience.

Having user messages disappear after sending would contribute to a better user experience (UX).

**Comment by Arindam200** [comment]
Can I work on this?

**Comment by jordan-pieces** [comment]
@Arindam200 would you be looking to combine this issue here, with this issue #61 as well? they are slightly related and the button could just be to reset the copilot chat. let me know if you have any thoughts here and we can get some solid steps together.

**Comment by jordan-pieces** [comment]
perfect sounds good! will assign you to them and you can connect them both to the same PR

**Comment by Arindam200** [comment]
Just to give an update, I'm working on this. 


Will send a PR Soon

**Comment by jordan-pieces** [comment]
sounds great @Arindam200, mention this issue when you have a PR up 👍
