### ISSUE TITLE
"Create Fresh Conversation" Button Inactive

### ISSUE THREAD

**Issue by Sophyia7** [pieces-app/example-ts#61]
### Problem statement
Copilot's "Create Fresh Conversation" button is inactive and doesn't respond when clicked. When clicked, the "Create Fresh Conversation" button should clear messages and chat and open up a new conversation.

Reach out if you need more information regarding this issue.

**Comment by Arindam200** [comment]
I would like to Give it a Try!

**Comment by jordan-pieces** [comment]
related to #60
