### ISSUE TITLE
Automatically refresh the Pieces Codesnippets list once a code snippet has been deleted + showcase a toast message for successful deletion of a code snippet

### ISSUE THREAD

**Issue by shivay-at-pieces** [pieces-app/example-ts#67]
Automatically refresh the Pieces Codesnippets list once a code snippet has been deleted + showcase a toast message / alertbox for successful deletion of a code snippet

At the moment when you delete any code snippet,  it doesn't reflect on the UI, you need to click on refresh button.

**Comment by RohanMishra315** [comment]
Hey @shivay-at-pieces I was asking does we have to make a new file for all this, if not then where should all changes happen ?

**Comment by agrim0312** [comment]
hey @shivay-at-pieces I have resolved the issue, just a alert box is left which i am implementing and will push later.

**Comment by shivay-at-pieces** [comment]
> Hey @shivay-at-pieces I was asking does we have to make a new file for all this, if not then where should all changes happen ?

So @RohanMishra315 you don't need to create a new file. You can implement the changes in the Delete.tsx file itself.
