### ISSUE TITLE
Add Improved Name Update Logic 

### ISSUE THREAD

**Issue by jordan-pieces** [pieces-app/example-ts#7]
## Issue 

![Screenshot 2023-11-17 at 3 34 03 PM](https://github.com/pieces-app/example-ts/assets/55861512/6a8be7ac-98f7-43c4-85b4-636c89824453)

You can see above here that right not the Update Name logic takes in both the new name that you would like to use, along with the id of the asset that you would like to have updated. 

A great update here would be adding an actively selected snippet, or current asset, that tracks the asset that is currently selected based on the user input, with a default as well. 

## Proposed Solutions

The result of this would be a single input that allows you to put in a new name and update the currently selected asset. 

Will need these things: 

- [ ] a 'currently active' state that is being checked and updates a value that references what the currently active assets ID is
- [ ] updates to the `renameAsset()` 

```tsx
function renameAsset(_name: string, _id: String){

    new Pieces.AssetsApi().assetsSnapshot({}).then(_assetList => {
        for (let i = 0; i < _assetList.iterable.length; i++) {
            if (_assetList.iterable[i].id == _id) {

                let _asset = _assetList.iterable[i];

                _asset.name = _name;

                new Pieces.AssetApi().assetUpdate({asset: _asset}).then(_updated => {
                    console.log("updated:", _updated);
                })
            }
        }
    })
}
```

- [ ] updates to `renameAssetInput()`

```tsx
function RenameAssetInput() {
    const [name, setNameValue] = useState('');
    const [id, setIdValue] = useState('');

    const handleNameChange = (event) => {
        setNameValue(event.target.value);
    };

    const handleIdChange = (event) => {
        setIdValue(event.target.value);
    };

    return (
        <>
            <p>Name:</p>
            <input value={name} style={{ width: '450px', verticalAlign: 'top' }} onChange={handleNameChange} />
            <p>ID:</p>
            <input value={id} style={{ width: '450px', verticalAlign: 'top' }} onChange={handleIdChange} />
            <button style={{ marginTop: '10px', maxWidth: '200px' }} onClick={() => renameAsset(name, id)}>Rename Snippet</button>
        </>

    );
}
```

**Comment by Pratere** [comment]
Hey @jordan-pieces I am opening a pull request to address this, I also modified the deleteAsset function to use the selected asset

**Comment by jordan-pieces** [comment]
@Pratere been a crazy day over here - but should have some time to go through this today/tomorrow morning ! Will let you know what i find, there were also some larger name updates that took place today so i will merge things and make sure the whole project is good to go before its on main !
