### ISSUE TITLE
Add Copilot Conversations Example

### ISSUE THREAD

**Issue by jordan-pieces** [pieces-app/example-ts#9]
## Issue 

We need a functional copilot chat that users can test and run inside of their browser. We will support the most basic format of copilot conversations - where it is a single chat. There does not need to be any context added, or any nonessential parameters. 

Personally I would love to have this added to another view - which may require more progress from: 
- #4 around updating the project structure to support more view 

## Steps 
- [x] Completion of UI updates to index on #35 
- [x] Added new container to hold UI
- [ ] UI created 
        - a simple scroll where the user can get conversation results and ask questions 
- [ ] Logic for Conversation requests

**Comment by Sophyia7** [comment]
@jordan-pieces I am Sophia and I would love to work on this issue.
